channels:
- https://repo.anaconda.com/pkgs/main
- https://repo.anaconda.com/pkgs/r
dependencies:
- anaconda::pandas
- conda-forge::pyyaml
- conda-forge::selenium
- conda-forge::webdriver-manager
- python=3.12
- kitmichi::pypdf2htmlex
- pytest
- flake8
- anaconda::sqlalchemy
- anaconda::psycopg2
