channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anaconda::pandas
  - anaconda::psycopg2
  - anaconda::sqlalchemy
  - conda-forge::prettytable
  - conda-forge::python-dotenv
  - conda-forge::pyyaml
  - conda-forge::ruff
  - conda-forge::selenium
  - conda-forge::webdriver-manager
  - flake8
  - kitmichi::pypdf2htmlex
  - pytest
  - python=3.12
  - conda-forge::icalendar
  - conda-forge::tabulate
