name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: my_password
          POSTGRES_DB: mydatabase
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        auto-update-conda: true
        activate-environment: test-environment
        environment-file: install_environment/environment.yml
    - name: Install dependencies
      run: |
        conda env update --file install_environment/environment.yml --name test-environment
    - name: Clone pdf2htmlEX repository
      run: |
        TEMP_DIR=$(mktemp -d)
        git clone https://github.com/telmop/pdf2htmlEX.git $TEMP_DIR/pdf2htmlEX
        cd $TEMP_DIR/pdf2htmlEX
        ./buildScripts/buildInstallLocallyApt
    - name: 
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        conda run -n test-environment flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=$TEMP_DIR
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        conda run -n test-environment flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=$TEMP_DIR
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Test with pytest
      env:
        PYTHONPATH: src
      run: |
        conda run -n test-environment pytest
